workspace = { members = ["utils"] }
[package]
name = "sugarust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.38.0"
glm = "0.2.3"
glfw = "0.55.0"
